In [3]:
import numpy as np
from scipy import linalg

**Exercise 2.1.1**

Suppose you want to interpolate the points $(-1,0)$,$(0,1)$,$(2,0)$,$(3,1)$, and $(4,2)$ by a polynomial of as low a degree as possible.

(a) Write out a linear system of equations for the coefficients of the interpolating polynomial.

$$\begin{align*}
c_1+c_2(-1)+c_3(-1)^2+c_4(-1)^3+c_5(-1)^4&=0\\
c_1+c_2(0)+c_3(0)^2+c_4(0)^3+c_5(0)^4&=1\\
c_1+c_2(2)+c_3(2)^2+c_4(2)^3+c_5(2)^4&=0\\
c_1+c_2(3)+c_3(3)^2+c_4(3)^3+c_5(3)^4&=1\\
c_1+c_2(4)+c_3(4)^2+c_4(4)^3+c_5(4)^4&=2
\end{align*}$$

(b) Solve the system in (a) numerically.

In [ ]:
x = np.array([-1, 0, 2, 3, 4])
y = np.array([0, 1, 0, 1, 2])

V = np.vander(x)

print(V)

c = linalg.solve(V, y)
p = np.poly1d(c)

print([float(p(x_i)) for x_i in x])

[[  1  -1   1  -1   1]
 [  0   0   0   0   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]
[-2.220446049250313e-16, 1.0, 7.771561172376096e-16, 0.9999999999999996, 2.000000000000001]


**Exercise 2.1.2**

(a) Say you want to find a cubic polynomial $p$ such that $p(-1)=-2$, $p'(-1)=1$, $p(1)=0$, and $p'(1)=-1$. (This is known as a *Hermite interpolant*.) Write out a linear system of equations for the coefficients of $p$.

$$\begin{align*}
c_1+c_2(-1)+c_3(-1)^2+c_4(-1)^3&=-2\\
c_1+c_2(1)+c_3(1)^2+c_4(1)^3&=0\\
c_2+2c_3(-1)+3c_4(-1)^2&=1\\
c_2+2c_3(1)+3c_4(1)^2&=-1
\end{align*}$$

(b) Numerically solve the linear system in part (a) and make a plot of $p$ over $-1\leq x\leq1$.

In [29]:
y = np.array([-2, 0, 1, -1])

"""
A = np.array([
    [1, -1, 1, -1],
    [1, 1, 1, 1],
    [0, 1, -2, 3],
    [0, 1, 2, 3]
])
"""

# do it in reverse cause poly1d is dumb
A = np.array([
    [-1, 1, -1, 1],
    [1, 1, 1, 1],
    [3, -2, 1, 0],
    [3, 2, 1, 0]
])

c = linalg.solve(A, y)
p = np.poly1d(c)
p_prime = p.deriv()

print([float(c) for c in [p(-1), p(1), p_prime(-1), p_prime(1)]])

[-1.9999999999999998, -2.220446049250313e-16, 1.0, -1.0000000000000002]


**Exercise 2.3.2**

Solve the following triangular systems by hand.

(b)

$$\begin{bmatrix}
4 & 0 & 0 & 0\\
1 & -2 & 0 & 0\\
-1 & 4 & 4 & 0\\
2 & -5 & 5 & 1
\end{bmatrix}\bold{x}=\begin{bmatrix}
-4\\1\\-3\\5
\end{bmatrix}$$

$$\begin{align*}
4x_1=-4&\to x_1=-1\\
x_1-2x_2=-1-2x_2=1&\to x_2=-1\\
-x_1+4x_2+4x_3=1-4+4x_3=-3&\to x_3=0\\
2x_1-5x_2+5x_3+x_4=-2+5+x_4=5&\to x_4=2
\end{align*}$$

**Exercise 2.3.3**

Use Function 2.3.1 or Function 2.3.2 to solve each system for $\bold{x}$ from the preceding exercise. Verify that the solution is correct by computing $\bold{b}-\bold{Ax}$.

In [12]:
def forwardsub(L, b):
    n = len(b)
    x = np.zeros(n)
    for i in range(n):
        s = L[i, :i] @ x[:i]
        x[i] = (b[i] - s) / L[i, i]
    return x

(b)

$$\begin{bmatrix}
4 & 0 & 0 & 0\\
1 & -2 & 0 & 0\\
-1 & 4 & 4 & 0\\
2 & -5 & 5 & 1
\end{bmatrix}\bold{x}=\begin{bmatrix}
-4\\1\\-3\\5
\end{bmatrix}$$

In [11]:
L = np.array([
    [4, 0, 0, 0],
    [1, -2, 0, 0],
    [-1, 4, 4, 0],
    [2, -5, 5, 1]
])
b = np.array([-4, 1, -3, 5])

x = forwardsub(L, b)
print(b - L @ x)

[0. 0. 0. 0.]


**Exercise 2.3.4**

Use Function 2.3.2 to solve the following systems. Verify that the solution is correct by computing $\bold{b}-\bold{Ux}$.

In [13]:
def backsub(U, b):
    n = len(b)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        s = U[i, i + 1:] @ x[i + 1:]
        x[i] = (b[i] - s) / U[i, i]
    return x

(a)

$$\begin{bmatrix}
3 & 1 & 0\\
0 & -1 & -2\\
0 & 0 & 3
\end{bmatrix}\bold{x}=\begin{bmatrix}1\\1\\6\end{bmatrix}$$

In [14]:
U = np.array([
    [3, 1, 0],
    [0, -1, -2],
    [0, 0, 3]
])
b = np.array([1, 1, 6])

x = backsub(U, b)
print(b - U @ x)

[0. 0. 0.]


**Exercise 2.5.1**

The following are asymptotic assertions about the limit $n\to\infty$. In each case, prove the statement true or false.

(a) $n^2=O(\ln n)$

False. If $n^2=O(\ln n)$, then $\lim_{n\to\infty}n^2/\ln n=\text{const } c$. By L'Hopital, this limit is unbounded. Thus, $n^2\neq O(\ln n)$

(b) $n^a=O(n^b)$ if $a\leq b$

True. If $a=b$, $\lim_{n\to\infty}n^a/n^b=1\to n^a=O(n^b)$. If $a<b$, $\lim_{n\to\infty}n^a/n^b=c_1\cdot\lim n^{a-1}/n^{b-1}=c_2\cdot\lim n^{a-2}/n^{b-2}=\cdots=c_{a-1}\cdot\lim n^{a-a+1}/n^{b-a+1}=c_a\cdot\lim 1/n^{b-a}=0\to n^a=O(n^b)$.

Basically repeated applications of L'Hopital's rule will result in a 0 limit, meaning it is bounded and thus $n^a$ is contained in $O(n^b)$.

(c) $e^n\sim e^{2n}$

False. $\lim_{n\to\infty}e^n/e^{2n}=\lim1/e^n=0\neq1\to e^n\nsim e^{2n}$

(d) $n+\sqrt{n}\sim n+2\sqrt{n}$

True. $\lim_{n\to\infty}(n+\sqrt{n})/(n+2\sqrt{n})=\lim n/n=1\to n+\sqrt{n}\sim n+2\sqrt{n}$.

**Exercise 2.5.5**

This problem is about the evaluation of a polynomial $c_1+c_2x+\cdots+c_nx^{n-1}$.

(a) Here is a little code to do the evaluation.

```python
y = c[0]
xpow = 1
for i in range(1, n):
    xpow *= x
    y += c[i] * xpow
```

Assuming that `x` is a scalar, how many flops does this function take, as a function of $n$?

`xpow *= x` is 1 FP multiplication, and `y += c[i] * xpow` is 1 FP addition and 1 FP multiplication for a total of 3 FLOPs per loop iteration. The loop iterates $n-1$ times, so $f(n)=3(n-1)$.

(b) Compare the count from (a) to the flop count for Horner's algorithm, Function 1.3.1.

Horner's algorithm is

```python
y = c[0]
for k in range(1, n):
    y = x * y + c[k]
```

`y = x * y + c[k]` is 1 FP multiplication and 1 FP addition for a total of 2 FLOPs per loop iteration. The loop iterates $n-1$ times, so $f(n)=2(n-1)$. The naiive algorithm takes 1.5 times longer.

**Exercise 2.6.1**

Perform by hand the pivoted LU factorization of each matrix.

(a)

$$\begin{bmatrix}
2 & 3 & 4\\
4 & 5 & 10\\
4 & 8 & 2
\end{bmatrix}$$

See attached picture of my work; I'm not typing allat that in TeX LOL.

**Exercise 2.7.4**

Prove that for all vectors $\bold{x}\in\mathbb{R}^n$,

(a) $\lVert\bold{x}\rVert_\infty\leq\lVert\bold{x}\rVert_2$

Let $\bold{x}_k$ be the largest absolute element of $\bold{x}$. $\lVert\bold{x}\rVert_\infty=|\bold{x}_k|$ by definition. $\lVert\bold{x}\rVert_2=(\sum \bold{x}_i^2)^{1/2}=(\bold{x}_1^2+\cdots+\bold{x}_k^2+\cdots+\bold{x}_n^2)^{1/2}$. Trivially observe how if all other $\bold{x}_j=0$ or if $\bold{x}$ is singleton, $\lVert\bold{x}\rVert_\infty=\lVert\bold{x}\rVert_2$. If this is not the case, $\lVert\bold{x}\rVert_2=|\bold{x}_k|+c$ where $c$ is some additional positive value from the summed $\bold{x}_j$&ZeroWidthSpace;s, making $\lVert\bold{x}\rVert_2>\lVert\bold{x}\rVert_\infty$.

(b) $\lVert\bold{x}\rVert_2\leq\lVert\bold{x}\rVert_1$

Make similar trivial observations of equality for the zero and singleton vector. Now assume $n\geq2$. This inequality is best shown between $(\lVert\bold{x}\rVert_2)^2$ and $(\lVert\bold{x}\rVert_1)^2$, which can be done because squaring preserves order. See that $(\lVert\bold{x}\rVert_2)^2=x_1^2+\cdots+x_n^2$. See that $(\lVert\bold{x}\rVert_1)^2=(|\bold{x}_1|+\cdots+|\bold{x}_n|)(|\bold{x}_1|+\cdots+|\bold{x}_n|)=\bold{x}_1^2+\sum_{i\neq1}|\bold{x}_1||\bold{x}_i|+\cdots+\bold{x}_n^2+\sum_{i\neq n}|\bold{x}_n||\bold{x}_i|$. Notice how this contains the 2-norm and additional, positive values, making $\lVert\bold{x}\rVert_2<\lVert\bold{x}\rVert_1$

**Exercise 2.7.6**

Let $$\bold{A}=\begin{bmatrix}-1 & 1\\2 & 2\end{bmatrix}$$

(a) Find all vectors satisfying $\lVert\bold{x}\rVert_\infty=1$ and $\lVert\bold{Ax}\rVert_\infty=\lVert\bold{A}\rVert_\infty$.

$\lVert \bold{A}\rVert_\infty$ is the max row-wise sum, which is $2+2=4$. We have $\lVert \bold{Ax}\rVert_\infty=\lVert[-x_1+x_2, 2x_1+2x_2]\rVert_\infty\to\max(|-x_1+x_2|, |2x_1+2x_2|)=4$ where $\lVert\bold{x}\rVert_\infty\to\max(|x_1|,|x_2|)=1$. Observe that $|-x_1+x_2|\neq4$, so $|2x_1+2x_2|=4$ is forced. The lines $2x_1+2x_2=4$ and $-(2x_1+2x_2)=4$ intersect the region $x_1\in[-1,1],x_2\in[-1,1]$ at exactly two points, $(1, 1)$ and $(-1, -1)$. Both of these meet the condition $\max(|x_1|,|x_2|)=1$, so the vectors $[1, 1]$ and $[-1, -1]$ are the only such $\bold{x}$.

(b) Find a vector satisfying $\lVert\bold{x}\rVert_1=1$ and $\lVert\bold{Ax}\rVert_1=\lVert\bold{A}\rVert_1$.

$\lVert\bold{A}\rVert_1$ is the max column-wise sum, which is $1+2=3$. We have $\lVert \bold{Ax}\rVert_\infty=\lVert[-x_1+x_2, 2x_1+2x_2]\rVert_\infty\to|-x_1+x_2|+|2x_1+2x_2|=3$ where $\lVert\bold{x}\rVert_1\to|x_1|+|x_2|=1$. The polygon $|-x_1+x_2|+|2x_1+2x_2|=3$ contains the point $(0, 1)$, which meets the conditions. Thus, $\bold{x}=[0, 1]$ is a valid such $\bold{x}$.

(c) Find a vector satisfying $\lVert\bold{x}\rVert_2=1$ such that $\lVert\bold{Ax}\rVert_2=\lVert\bold{A}\rVert_2$. (Hint: Use the definition of $\lVert\bold{A}\rVert_2$ as the maximum of $\lVert\bold{Ax}\rVert_2$ over unit vectors, and parameterize the unit vectors as $(\cos(\theta),\sin(\theta))$. Then $\lVert\bold{Ax}\rVert_2^2$ is a function of $\theta$ that is easy to maximize.)

$\bold{Ax}$ parameterized is $[-\cos\theta+\sin\theta, 2\cos\theta+2\sin\theta]$. $\lVert\bold{Ax}\rVert_2^2=(-\cos\theta+\sin\theta)^2+(2\cos\theta+2\sin\theta)^2=5+6\sin\theta\cos\theta$. The derivative of this is $6(\cos^2\theta-\sin^2\theta)$ with a root at $\pi/4$, meaning $\lVert\bold{Ax}\rVert_2^2$ is maximized when $\theta=\pi/4$. $\bold{x}=[\cos(\pi/4),\sin(\pi/4)]$ is a valid such $\bold{x}$.