**Exercise 2.1.1**

Suppose you want to interpolate the points $(-1,0)$,$(0,1)$,$(2,0)$,$(3,1)$, and $(4,2)$ by a polynomial of as low a degree as possible.

(a) Write out a linear system of equations for the coefficients of the interpolating polynomial.

$$\begin{align*}
c_1+c_2(-1)+c_3(-1)^2+c_4(-1)^3+c_5(-1)^4&=0\\
c_1+c_2(0)+c_3(0)^2+c_4(0)^3+c_5(0)^4&=1\\
c_1+c_2(2)+c_3(2)^2+c_4(2)^3+c_5(2)^4&=0\\
c_1+c_2(3)+c_3(3)^2+c_4(3)^3+c_5(3)^4&=1\\
c_1+c_2(4)+c_3(4)^2+c_4(4)^3+c_5(4)^4&=2
\end{align*}$$

(b) Solve the system in (a) numerically.

In [18]:
import numpy as np
from scipy import linalg

x = np.array([-1, 0, 2, 3, 4])
y = np.array([0, 1, 0, 1, 2])

V = np.vander(x)

print(V)

c = linalg.solve(V, y)
p = np.poly1d(c)

print([float(p(x_i)) for x_i in x])

[[  1  -1   1  -1   1]
 [  0   0   0   0   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]
[-2.220446049250313e-16, 1.0, 7.771561172376096e-16, 0.9999999999999996, 2.000000000000001]


**Exercise 2.1.2**

(a) Say you want to find a cubic polynomial $p$ such that $p(-1)=-2$, $p'(-1)=1$, $p(1)=0$, and $p'(1)=-1$. (This is known as a *Hermite interpolant*.) Write out a linear system of equations for the coefficients of $p$.

$$\begin{align*}
c_1+c_2(-1)+c_3(-1)^2+c_4(-1)^3&=-2\\
c_1+c_2(1)+c_3(1)^2+c_4(1)^3&=0\\
c_2+2c_3(-1)+3c_4(-1)^2&=1\\
c_2+2c_3(1)+3c_4(1)^2&=-1
\end{align*}$$

(b) Numerically solve the linear system in part (a) and make a plot of $p$ over $-1\leq x\leq1$.

In [29]:
y = np.array([-2, 0, 1, -1])

"""
A = np.array([
    [1, -1, 1, -1],
    [1, 1, 1, 1],
    [0, 1, -2, 3],
    [0, 1, 2, 3]
])
"""

# do it in reverse cause poly1d is dumb
A = np.array([
    [-1, 1, -1, 1],
    [1, 1, 1, 1],
    [3, -2, 1, 0],
    [3, 2, 1, 0]
])

c = linalg.solve(A, y)
p = np.poly1d(c)
p_prime = p.deriv()

print([float(c) for c in [p(-1), p(1), p_prime(-1), p_prime(1)]])

[-1.9999999999999998, -2.220446049250313e-16, 1.0, -1.0000000000000002]
